version: "3.8"
services:
  curtain:
    image: curtain-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - curtain-net

networks:
  curtain-net:
