---
- name: Deploy Frontend with Docker Compose and Self-Signed SSL Certificate
  hosts: all
  become: true
  vars:
    email: your-email@example.com
    domain: your-domain.com

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
          - openssl
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker's APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clone the repository
      git:
        repo: 'https://github.com/noatgnu/curtain.git'
        dest: /opt/curtain
        version: main

    - name: Copy docker-compose.yml to the target directory
      copy:
        content: |
          version: "3.8"
          services:
            curtain:
              image: curtain-app
              restart: unless-stopped
              build:
                context: .
                dockerfile: Dockerfile
              ports:
                - "80:80"
                - "443:443"
              networks:
                - curtain-net

          networks:
            curtain-net:
        dest: /opt/curtain/docker-compose.yml

    - name: Generate self-signed SSL certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /opt/curtain/npm/letsencrypt/live/{{ domain }}/privkey.pem
        -out /opt/curtain/npm/letsencrypt/live/{{ domain }}/fullchain.pem
        -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN={{ domain }}"

    - name: Start Docker Compose
      docker_compose:
        project_src: /opt/curtain
        state: present
        restarted: true

    - name: Set up cron job for renewing self-signed SSL certificate
      cron:
        name: "Renew self-signed SSL certificate"
        minute: "0"
        hour: "0"
        day: "1"
        month: "*/12"
        weekday: "*"
        job: >
          openssl req -x509 -nodes -days 365 -newkey rsa:2048
          -keyout /opt/curtain/npm/letsencrypt/live/{{ domain }}/privkey.pem
          -out /opt/curtain/npm/letsencrypt/live/{{ domain }}/fullchain.pem
          -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN={{ domain }}"
          && docker-compose -f /opt/curtain/docker-compose.yml restart
